import Foundation

// MARK: - AWS Module
//
// Syncs AWS CLI configuration by downloading aws-profiles.toml from the
// private GitHub repo, parsing it, and generating ~/.aws/config with
// credential_process entries that delegate to the 1Password credential helper.

actor AWSModule: SyncModule {
    nonisolated var name: String { "AWS" }

    private let opCLI = OnePasswordCLI()
    private let github = GitHubClient()

    // MARK: - Errors

    enum AWSError: Error, LocalizedError {
        case configGenerationFailed(String)

        var errorDescription: String? {
            switch self {
            case .configGenerationFailed(let reason): return "AWS config generation failed: \(reason)"
            }
        }
    }

    // MARK: - Sync

    func sync() async -> SyncResult {
        guard NetworkMonitor.shared.isConnected else {
            logger.notice("AWS sync skipped: no network")
            return .skipped("No network")
        }

        logger.notice("Starting AWS sync")

        do {
            try FileManager.default.createDirectory(at: Config.configDir, withIntermediateDirectories: true)
            try FileManager.default.createDirectory(
                at: FileManager.default.homeDirectoryForCurrentUser.appendingPathComponent(".aws"),
                withIntermediateDirectories: true
            )

            try await opCLI.checkAuthenticated()
            logger.notice("1Password authenticated")

            let helperPath = Config.configDir.appendingPathComponent("app/\(Config.helperName)")
            let configTemplate = try await github.download(filePath: "config/aws-profiles.toml")
            logger.notice("Downloaded aws-profiles.toml")

            let config = try await generateAWSConfig(from: configTemplate, helperPath: helperPath.path)
            logger.notice("Generated AWS config with \(config.components(separatedBy: "[profile").count - 1) profiles")

            try config.write(to: Config.awsConfigPath, atomically: true, encoding: .utf8)
            try FileManager.default.setAttributes([.posixPermissions: 0o600], ofItemAtPath: Config.awsConfigPath.path)
            logger.notice("Deployed ~/.aws/config")

            return .success("AWS synced")

        } catch {
            logger.error("AWS sync failed: \(error.localizedDescription)")
            return .failure(error.localizedDescription)
        }
    }

    // MARK: - Config Generation

    private func generateAWSConfig(from toml: String, helperPath: String) async throws -> String {
        var config = "# \(Config.orgName) AWS Configuration\n"
        config += "# Generated by \(Config.orgName) Config Sync\n"
        config += "# Credentials managed by 1Password\n\n"

        let profiles = TOMLParser.parseArrayOfTables(toml, section: "profiles")

        if profiles.isEmpty {
            logger.warning("No profiles found in aws-profiles.toml")
        }

        for profile in profiles {
            config += try await formatProfile(profile, helperPath: helperPath)
        }

        return config
    }

    private func formatProfile(_ profile: TOMLParser.Entry, helperPath: String) async throws -> String {
        guard let name = profile["name"],
              let region = profile["region"],
              let output = profile["output"],
              let itemTitle = profile["item_title"],
              let vault = profile["vault"] else {
            logger.warning("Skipping incomplete AWS profile: \(profile)")
            return ""
        }

        var result = ""
        if name == "default" {
            result += "[default]\n"
        } else {
            result += "[profile \(name)]\n"
        }

        result += "region = \(region)\n"
        result += "output = \(output)\n"
        result += "credential_process = \(helperPath) \"\(itemTitle)\" \"\(vault)\"\n"

        // Look up MFA serial if has_mfa is true
        if profile["has_mfa"] == "true" {
            if let mfaSerial = try? await opCLI.getMFASerial(item: itemTitle, vault: vault), !mfaSerial.isEmpty {
                result += "mfa_serial = \(mfaSerial)\n"
                logger.notice("Found MFA serial for profile: \(name)")
            }
        }

        result += "\n"
        logger.notice("Configured AWS profile: \(name)")
        return result
    }
}
